# Generated by Django 3.2.7 on 2021-10-27 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eNews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé'),
        ),
        migrations.AddField(
            model_name='statut',
            name='mix_statuts',
            field=models.ManyToManyField(blank=True, default=None, to='eNews.Statut', verbose_name='Statuts associés'),
        ),
        migrations.AddField(
            model_name='doc',
            name='approbateur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Doc_approbateur', to=settings.AUTH_USER_MODEL, verbose_name='Approbateur'),
        ),
        migrations.AddField(
            model_name='doc',
            name='destinataires',
            field=models.ManyToManyField(blank=True, default=None, related_name='Doc_destinataires', to='eNews.Statut', verbose_name='Destinataires'),
        ),
        migrations.AddField(
            model_name='doc',
            name='doctype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='of_doctype', to='eNews.doctype', verbose_name='Type de document'),
        ),
        migrations.AddField(
            model_name='doc',
            name='favorite_for',
            field=models.ManyToManyField(blank=True, default=None, related_name='doc_favorite_for', to=settings.AUTH_USER_MODEL, verbose_name='Liste des utilisateurs ayant ajouté cette Doc Ops à leurs favoris'),
        ),
        migrations.AddField(
            model_name='doc',
            name='redacteur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Doc_redacteur', to=settings.AUTH_USER_MODEL, verbose_name='Rédacteur'),
        ),
        migrations.AddField(
            model_name='doc',
            name='update_of',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_by', to='eNews.doc', verbose_name='Référence du document remplacé par cette doc'),
        ),
        migrations.AddField(
            model_name='doc',
            name='verificateurs',
            field=models.ManyToManyField(blank=True, default=None, related_name='Doc_verificateurs', to=settings.AUTH_USER_MODEL, verbose_name='Vérificateurs'),
        ),
        migrations.AddField(
            model_name='doc',
            name='who_read_it',
            field=models.ManyToManyField(blank=True, default=None, related_name='doc_who_read_it', to=settings.AUTH_USER_MODEL, verbose_name='Liste des utilisateurs ayant lu la Doc Ops'),
        ),
        migrations.AddIndex(
            model_name='doc',
            index=models.Index(fields=['year_ref', 'doctype', 'number_ref'], name='eNews_doc_year_re_a86279_idx'),
        ),
        migrations.AddIndex(
            model_name='doc',
            index=models.Index(fields=['-publication_date'], name='eNews_doc_publica_358d53_idx'),
        ),
    ]
