# Generated by Django 3.2.7 on 2021-11-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eNews', '0003_doc_search_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctype',
            name='archive_path',
            field=models.CharField(blank=True, help_text="Utilisez le mot-clé ${YEAR} qui sera remplacé par l'année de publication du document", max_length=250, null=True, verbose_name="Chemin vers l'archivage long durée"),
        ),
    ]
