# Generated by Django 3.2.11 on 2022-01-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eNews', '0004_alter_doctype_archive_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctype',
            name='reference_format',
            field=models.CharField(default='YYTNNN', help_text="'YYYY' : année sur 4 charactères<br/>'YY' : les 2 derniers chiffres de l'année (2021 -> 21)<br/>'T' : Abbréviation du type de document (2, 3 caractères : NI, CPG, ...)<br/>'NNN' : index du document codé sur autant de caractères (NNN : 001, NNNN: 0001)<br/>Les autres caractères sont autorisés et seront intégrés tels quels dans la référence du document (ex : tirets, slash, autres lettres...", max_length=25, verbose_name='Format utilisé pour les références du documents'),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='full_name',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='doctype',
            name='short_name',
            field=models.CharField(default='', max_length=15, null=True, unique=True, verbose_name='Abréviation'),
        ),
    ]
