# Generated by Django 3.2.12 on 2022-03-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eNews', '0006_auto_20220131_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='destinataires',
            field=models.ManyToManyField(blank=True, default=None, related_name='doc_destinataires', to='eNews.Statut', verbose_name='Destinataires'),
        ),
        migrations.AlterField(
            model_name='statut',
            name='mix_statuts',
            field=models.ManyToManyField(blank=True, default=None, related_name='parent_statuts', to='eNews.Statut', verbose_name='Statuts associés'),
        ),
    ]
