# Generated by Django 3.2.12 on 2022-03-16 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eNews', '0007_auto_20220313_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='file',
            field=models.FileField(blank=True, max_length=251, null=True, upload_to='enews_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Doc (au format PDF)'),
        ),
    ]
