# Generated by Django 3.2.7 on 2021-10-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Titre')),
                ('icon', models.CharField(blank=True, choices=[('AccountBoxOutline', 'AccountBoxOutline'), ('AlertBoxOutline', 'AlertBoxOutline'), ('AlphaAboxOutline', 'AlphaAboxOutline'), ('AlphaBboxOutline', 'AlphaBboxOutline'), ('AlphaCboxOutline', 'AlphaCboxOutline'), ('AlphaDboxOutline', 'AlphaDboxOutline'), ('AlphaEboxOutline', 'AlphaEboxOutline'), ('AlphaFboxOutline', 'AlphaFboxOutline'), ('AlphaGboxOutline', 'AlphaGboxOutline'), ('AlphaHboxOutline', 'AlphaHboxOutline'), ('AlphaIboxOutline', 'AlphaIboxOutline'), ('AlphaJboxOutline', 'AlphaJboxOutline'), ('AlphaKboxOutline', 'AlphaKboxOutline'), ('AlphaLboxOutline', 'AlphaLboxOutline'), ('AlphaMboxOutline', 'AlphaMboxOutline'), ('AlphaNboxOutline', 'AlphaNboxOutline'), ('AlphaOboxOutline', 'AlphaOboxOutline'), ('AlphaPboxOutline', 'AlphaPboxOutline'), ('AlphaQboxOutline', 'AlphaQboxOutline'), ('AlphaRboxOutline', 'AlphaRboxOutline'), ('AlphaSboxOutline', 'AlphaSboxOutline'), ('AlphaTboxOutline', 'AlphaTboxOutline'), ('AlphaUboxOutline', 'AlphaUboxOutline'), ('AlphaVboxOutline', 'AlphaVboxOutline'), ('AlphaWboxOutline', 'AlphaWboxOutline'), ('AlphaXboxOutline', 'AlphaXboxOutline'), ('AlphaYboxOutline', 'AlphaYboxOutline'), ('AlphaZboxOutline', 'AlphaZboxOutline'), ('ChartBoxOutline', 'ChartBoxOutline'), ('CheckBoxOutline', 'CheckBoxOutline'), ('CircleBoxOutline', 'CircleBoxOutline'), ('CloseBoxOutline', 'CloseBoxOutline'), ('HeartBoxOutline', 'HeartBoxOutline'), ('MinusBoxOutline', 'MinusBoxOutline'), ('MusicBoxOutline', 'MusicBoxOutline'), ('Numeric0BoxOutline', 'Numeric0BoxOutline'), ('Numeric1BoxOutline', 'Numeric1BoxOutline'), ('Numeric2BoxOutline', 'Numeric2BoxOutline'), ('Numeric3BoxOutline', 'Numeric3BoxOutline'), ('Numeric4BoxOutline', 'Numeric4BoxOutline'), ('Numeric5BoxOutline', 'Numeric5BoxOutline'), ('Numeric6BoxOutline', 'Numeric6BoxOutline'), ('Numeric7BoxOutline', 'Numeric7BoxOutline'), ('Numeric8BoxOutline', 'Numeric8BoxOutline'), ('Numeric9BoxOutline', 'Numeric9BoxOutline'), ('PlusBoxOutline', 'PlusBoxOutline'), ('PoundBoxOutline', 'PoundBoxOutline'), ('StarBoxOutline', 'StarBoxOutline')], help_text="<a href='https://materialdesignicons.com/'>Aperçu des icônes</a>", max_length=100, null=True, verbose_name='Icon')),
                ('rank', models.PositiveIntegerField(verbose_name='Rang')),
                ('query', models.CharField(max_length=250, verbose_name='Recherche')),
            ],
        ),
    ]
