# Generated by Django 3.2.12 on 2022-03-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eNews', '0010_auto_20220316_1458'),
        ('nav', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navitem',
            options={'ordering': ['rank', 'title'], 'verbose_name': 'Recherche enregistrée', 'verbose_name_plural': 'Recherches enregistrées'},
        ),
        migrations.AlterField(
            model_name='navitem',
            name='query',
            field=models.CharField(help_text="Sous la forme '?keyword=value&other_keyword=other_value'<br/>Voir l'URL de eNews quand on choisit des filtres personnalisés", max_length=250, verbose_name='Recherche'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='rank',
            field=models.PositiveIntegerField(default=0, verbose_name='Rang'),
        ),
        migrations.CreateModel(
            name='DoctypeFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25, verbose_name='Intitulé')),
                ('icon', models.CharField(blank=True, choices=[('AccountBoxOutline', 'AccountBoxOutline'), ('AlertBoxOutline', 'AlertBoxOutline'), ('AlphaAboxOutline', 'AlphaAboxOutline'), ('AlphaBboxOutline', 'AlphaBboxOutline'), ('AlphaCboxOutline', 'AlphaCboxOutline'), ('AlphaDboxOutline', 'AlphaDboxOutline'), ('AlphaEboxOutline', 'AlphaEboxOutline'), ('AlphaFboxOutline', 'AlphaFboxOutline'), ('AlphaGboxOutline', 'AlphaGboxOutline'), ('AlphaHboxOutline', 'AlphaHboxOutline'), ('AlphaIboxOutline', 'AlphaIboxOutline'), ('AlphaJboxOutline', 'AlphaJboxOutline'), ('AlphaKboxOutline', 'AlphaKboxOutline'), ('AlphaLboxOutline', 'AlphaLboxOutline'), ('AlphaMboxOutline', 'AlphaMboxOutline'), ('AlphaNboxOutline', 'AlphaNboxOutline'), ('AlphaOboxOutline', 'AlphaOboxOutline'), ('AlphaPboxOutline', 'AlphaPboxOutline'), ('AlphaQboxOutline', 'AlphaQboxOutline'), ('AlphaRboxOutline', 'AlphaRboxOutline'), ('AlphaSboxOutline', 'AlphaSboxOutline'), ('AlphaTboxOutline', 'AlphaTboxOutline'), ('AlphaUboxOutline', 'AlphaUboxOutline'), ('AlphaVboxOutline', 'AlphaVboxOutline'), ('AlphaWboxOutline', 'AlphaWboxOutline'), ('AlphaXboxOutline', 'AlphaXboxOutline'), ('AlphaYboxOutline', 'AlphaYboxOutline'), ('AlphaZboxOutline', 'AlphaZboxOutline'), ('ChartBoxOutline', 'ChartBoxOutline'), ('CheckBoxOutline', 'CheckBoxOutline'), ('CircleBoxOutline', 'CircleBoxOutline'), ('CloseBoxOutline', 'CloseBoxOutline'), ('HeartBoxOutline', 'HeartBoxOutline'), ('MinusBoxOutline', 'MinusBoxOutline'), ('MusicBoxOutline', 'MusicBoxOutline'), ('Numeric0BoxOutline', 'Numeric0BoxOutline'), ('Numeric1BoxOutline', 'Numeric1BoxOutline'), ('Numeric2BoxOutline', 'Numeric2BoxOutline'), ('Numeric3BoxOutline', 'Numeric3BoxOutline'), ('Numeric4BoxOutline', 'Numeric4BoxOutline'), ('Numeric5BoxOutline', 'Numeric5BoxOutline'), ('Numeric6BoxOutline', 'Numeric6BoxOutline'), ('Numeric7BoxOutline', 'Numeric7BoxOutline'), ('Numeric8BoxOutline', 'Numeric8BoxOutline'), ('Numeric9BoxOutline', 'Numeric9BoxOutline'), ('PlusBoxOutline', 'PlusBoxOutline'), ('PoundBoxOutline', 'PoundBoxOutline'), ('StarBoxOutline', 'StarBoxOutline')], help_text="<a href='https://materialdesignicons.com/'>Aperçu des icônes</a>", max_length=100, null=True, verbose_name='Icon')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='Rang')),
                ('doctypes', models.ManyToManyField(to='eNews.DocType', verbose_name='Types de documents à afficher')),
            ],
            options={
                'verbose_name': 'Filtre Type de document',
                'verbose_name_plural': 'Filtres Type de document',
                'ordering': ['rank', 'label'],
            },
        ),
    ]
